apiVersion: kustomize.config.k8s.io/v1beta1
kind:       Kustomization
resources:
  - all.yaml
patchesStrategicMerge:
  - replace_crds.yaml
configMapGenerator:
  - name: longhorn-dashboard-cm
    files:
      - dashboards/longhorn-dashboard.json
