apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    plugin:
      name: kustomized-helm
      env:
        - name: HELM_TEMPLATE_ARGS
          value: --include-crds
    repoURL: https://github.com/malteesch/infrastructure.git
    targetRevision: HEAD
    path: cluster/prometheus/stack
