---
- name: Install zsh
  become: true
  register: install_zsh
  community.general.pacman:
    update_cache: true
    name: zsh
    state: latest

- name: Disable password for chsh
  become: true
  when: install_zsh.changed
  lineinfile:
    path: /etc/pam.d/chsh
    regex: '^auth\s+required\s+pam_shells.so$'
    line: 'auth       sufficient   pam_shells.so'

- name: Set new login shell
  when: install_zsh.changed
  shell:
    cmd: "chsh -s /usr/bin/zsh"

- name: Reenable password for chsh
  become: true
  when: install_zsh.changed
  lineinfile:
    path: /etc/pam.d/chsh
    regex: '^auth\s+sufficient\s+pam_shells.so$'
    line: 'auth       required   pam_shells.so'

- name: Install oh-my-zsh
  register: install_omz
  shell:
    cmd: '$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)'
    creates: "$HOME/.oh-my-zsh/oh-my-zsh.sh"

- name: Install zsh autosuggestions plugin
  when: install_omz.changed
  shell:
    cmd: 'git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions'
    creates: '.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh'

- name: Install zsh syntax-highlighting plugin
  when: install_omz.changed
  shell:
    cmd: 'git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting'
    creates: '.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh'

- name: Add zsh config files
  copy:
    src: templates/.zshrc
    dest: "$HOME/.zshrc"
