---
- file:
    path: '$HOME/.local/bin/'
    state: directory

- unarchive:
    remote_src: true
    src: https://github.com/cantino/mcfly/releases/download/v0.6.0/mcfly-v0.6.0-x86_64-unknown-linux-musl.tar.gz
    dest: '$HOME/.local/bin/'

- lineinfile:
    path: '$HOME/.zshrc'
    line: 'export MCFLY_KEY_SCHEME=vim'
    state: present

- lineinfile:
    path: '$HOME/.zshrc'
    line: 'export MCFLY_FUZZY=2'
    state: present

- lineinfile:
    path: '$HOME/.zshrc'
    line: 'eval "$(mcfly init zsh)"'
    state: present
