---
- yum_repository:
    name: docker-ce-stable
    description: docker-ce-stable
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/fedora/gpg
  become: true

- dnf:
    name:
      - docker-ce
      - docker-compose-plugin
    state: latest
  become: true
