---
- ansible.builtin.file:
    name: '$HOME/sdks'
    state: directory

- import_tasks: graalvm.yml

- import_tasks: bazel.yml

- import_tasks: docker.yml

- ansible.builtin.dnf:
    name:
      - golang
      - kubernetes-client
      - perl-CPAN
      - dnf-plugins-core
    state: present
  become: true

- community.general.ini_file:
    path: '$HOME/.gitconfig'
    section: user
    option: email
    value: accounts@malteesch.de

- community.general.ini_file:
    path: '$HOME/.gitconfig'
    section: user
    option: name
    value: Malte Esch
