---
- ansible.builtin.file:
    name: '$HOME/sdks'
    state: directory

- import_tasks: graalvm.yml

- import_tasks: bazel.yml

- ansible.builtin.dnf:
    name:
      - kubernetes-client
      - perl-CPAN
    state: present
  become: true
