---
- ansible.builtin.file:
    path: '$HOME/.ssh'
    state: directory

- community.crypto.openssh_keypair:
    path: '$HOME/.ssh/id_rsa'
    size: 4096

- import_tasks: gpg_key.yml

- name: Install basic packages
  become: true
  ansible.builtin.dnf:
    name:
      - tldr
    state: latest
