---
- become: true
  rpm_key:
    state: present
    key: https://downloads.1password.com/linux/keys/1password.asc

- become: true
  yum_repository:
    name: 1password
    description: 1Password Stable Channel
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc

- name: Install 1password
  become: true
  ansible.builtin.dnf:
    name: 1password
    state: latest
