apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  configManagementPlugins: |
    - name: kustomized-helm
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: [sh, -c]
        args: ["helm template --release-name --namespace=$ARGOCD_APP_NAMESPACE $HELM_TEMPLATE_ARGS $ARGOCD_APP_NAME . > all.yaml && kustomize build"]
